apiVersion: batch/v1	
kind: Job	
metadata: 	
  name: fuseclassroom-testrail-prod	
  namespace: testrail-prod
spec:	
  template:	
    metadata:	
      labels:	
        app: fuseclassroom-testrail-prod	
    spec:	
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:	
      - name: rubicon-inference-job	
        image: "887384599564.dkr.ecr.us-east-1.amazonaws.com/fuseclassroom-testrail-prod:v1" 
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        resources:
          limits:
            memory: 4000Mi
            cpu: "2"
          requests:
            memory: 1500Mi
            cpu: 15
00m
      restartPolicy: Never	
  backoffLimit: 4
